export subject1="8 9 * 9 - 9 - 9 - 4 - 1 +"
export subject2="7 7 * 7 -"
export subject3="1 2 * 2 / 2 * 2 4 - +"
export subject4="(1 + 1)"
export test1="1 2 3 4 qqwe + + + +"
export test2="1 a 3 4 + + +"
export test3="1 2 3 4 + + + +"
export test4="1 +2 3 4 + + +"
export test5="1 -2 3 4 + + +"
export test6="1 2 3 4 + + ++"
export test7="1 2 3 4 + + + +"
export test8="1 2 3 4 + + + + + "
export test9="1 2 3 4 + "
export test10="1 2 3 4 + + + "


make re

echo "$> ./RPN " "$subject1"
 ./RPN "$subject1"
echo "$> ./RPN " "$subject2"
 ./RPN "$subject2"
echo "$> ./RPN " "$subject3"
 ./RPN "$subject3"
echo "$> ./RPN " "$subject4"
 ./RPN "$subject4"
echo "$> ./RPN " "$test1"
 ./RPN "$test1"
echo "$> ./RPN " "$test2"
 ./RPN "$test2"
echo "$> ./RPN " "$test3"
 ./RPN "$test3"
echo "$> ./RPN " "$test4"
 ./RPN "$test4"
echo "$> ./RPN " "$test5"
 ./RPN "$test5"
echo "$> ./RPN " "$test6"
 ./RPN "$test6"
echo "$> ./RPN " "$test7"
 ./RPN "$test7"
echo "$> ./RPN " "$test8"
 ./RPN "$test8"
echo "$> ./RPN " "$test9"
 ./RPN "$test9"
echo "$> ./RPN " "$test10"
 ./RPN "$test10"
